@baseUrl = http://localhost:3000

### Login the default user & define a Request Variable
# @name eleonore
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email":"Caroline.line@student.vinci.be",
  "password":"mdpuser.1"
}

> {%
  client.global.set("carolineToken", response.body.token);
%}

### get all companies
GET http://localhost:3000/companies/all
Authorization: {{carolineToken}}

### get all available companies for eleonore
GET http://localhost:3000/companies/all/user
Authorization: {{carolineToken}}

### get one company by id
GET http://localhost:3000/companies/2
Authorization: {{carolineToken}}