@baseUrl = http://localhost:3000

### Login the default user & define a Request Variable
# @name eleonore
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email":"eleonore.martin@vinci.be",
  "password":"123"
}

> {%
  client.global.set("eleonoreToken", response.body.token);
%}

### Create one contact
POST {{baseUrl}}/contacts/start
Content-Type: application/json
Authorization: {{eleonoreToken}}

{
  "company": "6",
  "student": "2"
}

### Unsupervise one contact
POST {{baseUrl}}/contacts/unsupervise
Content-Type: application/json
Authorization: {{eleonoreToken}}

{
  "contactId":"3"
}

### Create one contact
POST {{baseUrl}}/contacts/turnDown
Content-Type: application/json
Authorization: {{eleonoreToken}}

{
  "contactId": "3",
  "reasonForRefusal": "your profil isn't corresponding to our demand"
}